services:
  springboot:
    build: .
    image: auth
    container_name: auth
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql
    container_name: mysql_auth
    environment:
      MYSQL_ROOT_PASSWORD: thgml0108^^*!
      MYSQL_DATABASE: auth
      MYSQL_PASSWORD: thgml0108^^*!
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    external:
      name: funfit
